fix: 🐛 add scroll to <FilterListValue>
keen/query-creator pull request #42
Opened 2021-02-10 15:08 UTC by apryka

https://metakeen.atlassian.net/browse/FEE-363

2021-02-11 14:55 UTC, mczapkowicz approved these changes

2021-02-11 15:26 UTC, dariuszlacheta approved these changes

2021-02-15 08:41 UTC, maciejrybaniec requested changes

2021-02-15 08:41 UTC, maciejrybaniec commented on src/components/Filters/components/FilterListValue/FilterListValue.styles.ts
> +  ${layout}
`;` should be placed here

2021-02-16 13:27 UTC, merged