fix: 🐛 Clear limit field on group by change
keen/query-creator pull request #99
Opened 2021-11-05 11:14 UTC by mczapkowicz

https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10/backlog?selectedIssue=FEE-845

2021-11-08 06:54 UTC, apryka approved these changes

2021-11-08 07:01 UTC, maciejrybaniec requested changes

2021-11-08 07:01 UTC, maciejrybaniec commented on src/components/Limit/Limit.tsx
>      };
The `limit` should be cleared when `group_by` do not contains the property used in `order_by`.

2021-11-10 10:32 UTC, apryka approved these changes

2021-11-10 11:57 UTC, merged